### ISSUE TITLE
When ohsome/OQT API is unavailable, a fitting message should be shown

### ISSUE THREAD

**Issue by mhhd2020** [GIScience/sketch-map-tool#2]
Currently calling the ohsome API results in the following response:
```
 {
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 500,
  "statusText": "Internal Server Error",
  "url": "https://api.ohsome.org/v1/metadata?",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for https://api.ohsome.org/v1/metadata?: 500 Internal Server Error",
  "error": {
    "timestamp": "2022-05-15T21:38:31.895+0000",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/metadata"
  }
}
```
While this should be detected by the sketch map tool and explained to the user, the following error resulted instead:
```
Traceback (most recent call last):
2022-05-15T21:36:40.819869300Z   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
2022-05-15T21:36:40.819875400Z     self.run()
2022-05-15T21:36:40.819877900Z   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
2022-05-15T21:36:40.819880000Z     self._target(*self._args, **self._kwargs)
2022-05-15T21:36:40.819882300Z   File "/app/analyses/run_analyses.py", line 135, in run_preparations_and_analyses
2022-05-15T21:36:40.819884400Z     time_str_full_yearly = metadata["extractRegion"]["temporalExtent"]["fromTimestamp"][0:10] + \
2022-05-15T21:36:40.819886600Z KeyError: 'extractRegion'
```

**Comment by matthiasschaub** [comment]
b95d4cae2f757e91edc66bf3af4a20666d7f295e
3defa3f906e651c14c8363ccea22fa70332130b6
