### ISSUE TITLE
upload-processing: communitcate to the user if result GeoJSON is empty (no sketches were detected)

### ISSUE THREAD

**Issue by solo2307** [GIScience/sketch-map-tool#342]
Include an exception for solutions where no markings are detected:

```
Speed: 9.5ms preprocess, 347.1ms inference, 0.6ms postprocess per image at shape (1, 3, 800, 672)
[2024-01-15 16:44:25,924: ERROR/ForkPoolWorker-1] Task sketch_map_tool.tasks.digitize_sketches[52534717-c366-494a-a6c9-78ccc59615fb] raised unexpected: UnboundLocalError("local variable 'crs' referenced before assignment")
Traceback (most recent call last):
  File "/Users/ygrinblat/mambaforge/envs/smt/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/ygrinblat/Documents/Git_repos/sketch-map-tool/sketch_map_tool/__init__.py", line 52, in __call__
    return self.run(*args, **kwargs)
  File "/Users/ygrinblat/Documents/Git_repos/sketch-map-tool/sketch_map_tool/tasks.py", line 143, in digitize_sketches
    return merge(l)
  File "/Users/ygrinblat/Documents/Git_repos/sketch-map-tool/sketch_map_tool/upload_processing/merge.py", line 18, in merge
    feature_collection["crs"] = crs
UnboundLocalError: local variable 'crs' referenced before assignment
```

**Comment by matthiasschaub** [comment]
Solution could be to check resulting numpy array or geojson if markings were detected and if not either:
1. raise an error + make sure it is handled in the front-end
2. or return empty geojsone -> which might by unexpected by the user

**Comment by solo2307** [comment]
I would prefer to go with solution number one.

**Comment by matthiasschaub** [comment]
Another solution could be to return a log file with additional information to the user (include it in the result zip file)

**Comment by matthiasschaub** [comment]
Succeeded by  #491
