### ISSUE TITLE
Simultaneously uploading multiple sketch maps (4x24) leads to sigkill

### ISSUE THREAD

**Issue by Gigaszi** [GIScience/sketch-map-tool#395]
When sedning multiple (in this case 16) sketch maps with OSM background to digitize locally, it runs after ~12 mins into this error:
```
ERROR - request.py - on_failure - Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL) Job: 5.')
sketch-map-tool-celery-1  | Traceback (most recent call last):
sketch-map-tool-celery-1  |   File "/home/smt/.conda/envs/smt/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
sketch-map-tool-celery-1  |     raise WorkerLostError(
sketch-map-tool-celery-1  | billiard.einfo.ExceptionWithTraceback: 
sketch-map-tool-celery-1  | """
sketch-map-tool-celery-1  | Traceback (most recent call last):
sketch-map-tool-celery-1  |   File "/home/smt/.conda/envs/smt/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
sketch-map-tool-celery-1  |     raise WorkerLostError(
sketch-map-tool-celery-1  | billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 5.
sketch-map-tool-celery-1  | """
```

**Comment by Gigaszi** [comment]
Sketch Map Image:
![9](https://github.com/GIScience/sketch-map-tool/assets/74006329/1645e016-b28c-4ffc-a90c-57e01fed9c20)
Map Frame:

![filename](https://github.com/GIScience/sketch-map-tool/assets/74006329/b241164e-97d7-49a0-81d1-0dcbcb0f7551)

**Comment by Gigaszi** [comment]
Sketch Map:
![1](https://github.com/GIScience/sketch-map-tool/assets/74006329/1cd3636b-6d73-4c42-9a5e-367634dc17df)
Map Frame:
![filename](https://github.com/GIScience/sketch-map-tool/assets/74006329/e40991db-ca60-4b1a-a448-1ea7c9be3fa0)

**Comment by matthiasschaub** [comment]
Addressed in part by 6f4fafbe88ec7733b800a59d4c2dbbad423f0741
