### ISSUE TITLE
Unsupported depth of input image error for multiple Sketch Map upload

### ISSUE THREAD

**Issue by Gigaszi** [GIScience/sketch-map-tool#396]
When uploading multiple Sketch Maps (here 16), this error occurs:

```
ERROR/ForkPoolWorker-4] Task sketch_map_tool.tasks.digitize_sketches[cac44771-268b-4a18-9f02-59d517832b1f] raised unexpected: error("OpenCV(4.9.0) /io/opencv/modules/imgproc/src/color.simd_helpers.hpp:94: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<1>; VDcn = cv::impl::{anonymous}::Set<3, 4>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'\n> Unsupported depth of input image:\n>     'VDepth::contains(depth)'\n> where\n>     'depth' is 6 (CV_64F)\n")
sketch-map-tool-celery-1  | Traceback (most recent call last):
sketch-map-tool-celery-1  |   File "/home/smt/.conda/envs/smt/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
sketch-map-tool-celery-1  |     R = retval = fun(*args, **kwargs)
sketch-map-tool-celery-1  |                  ^^^^^^^^^^^^^^^^^^^^
sketch-map-tool-celery-1  |   File "/opt/smt/sketch_map_tool/__init__.py", line 58, in __call__
sketch-map-tool-celery-1  |     return self.run(*args, **kwargs)
sketch-map-tool-celery-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
sketch-map-tool-celery-1  |   File "/opt/smt/sketch_map_tool/tasks.py", line 183, in digitize_sketches
sketch-map-tool-celery-1  |     r: NDArray = detect_markings(
sketch-map-tool-celery-1  |                  ^^^^^^^^^^^^^^^^
sketch-map-tool-celery-1  |   File "/opt/smt/sketch_map_tool/upload_processing/detect_markings.py", line 34, in detect_markings
sketch-map-tool-celery-1  |     image = Image.fromarray(cv2.cvtColor(sketch_map_frame, cv2.COLOR_BGR2RGB))
sketch-map-tool-celery-1  |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sketch-map-tool-celery-1  | cv2.error: OpenCV(4.9.0) /io/opencv/modules/imgproc/src/color.simd_helpers.hpp:94: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<1>; VDcn = cv::impl::{anonymous}::Set<3, 4>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
sketch-map-tool-celery-1  | > Unsupported depth of input image:
sketch-map-tool-celery-1  | >     'VDepth::contains(depth)'
sketch-map-tool-celery-1  | > where
sketch-map-tool-celery-1  | >     'depth' is 6 (CV_64F)

```

**Comment by Gigaszi** [comment]
Sketch Map:
![4](https://github.com/GIScience/sketch-map-tool/assets/74006329/ef5f16e5-ab3e-4657-930e-36b984eb1f2f)
Map Frame:
![filename](https://github.com/GIScience/sketch-map-tool/assets/74006329/443f452a-ccac-4734-b089-da56d3c86cd6)
