### ISSUE TITLE
TimeOutError for multiple sketch maps of urban area

### ISSUE THREAD

**Issue by Gigaszi** [GIScience/sketch-map-tool#403]
When digitizing multiple (here 4) sketch maps of an urban error, this error occurs:
```
sketch-map-tool-celery-1  | 2024-03-25 12:40:20,361 - ERROR - request.py - on_failure - Task handler raised error: TimeLimitExceeded(900)
sketch-map-tool-celery-1  | Traceback (most recent call last):
sketch-map-tool-celery-1  |   File "/home/smt/.conda/envs/smt/lib/python3.11/site-packages/billiard/pool.py", line 683, in on_hard_timeout
sketch-map-tool-celery-1  |     raise TimeLimitExceeded(job._timeout)
sketch-map-tool-celery-1  | billiard.einfo.ExceptionWithTraceback: 
sketch-map-tool-celery-1  | """
sketch-map-tool-celery-1  | Traceback (most recent call last):
sketch-map-tool-celery-1  |   File "/home/smt/.conda/envs/smt/lib/python3.11/site-packages/billiard/pool.py", line 683, in on_hard_timeout
sketch-map-tool-celery-1  |     raise TimeLimitExceeded(job._timeout)
sketch-map-tool-celery-1  | billiard.exceptions.TimeLimitExceeded: TimeLimitExceeded(900,)
sketch-map-tool-celery-1  | """
sketch-map-tool-celery-1  | 2024-03-25 12:40:20,362 - ERROR - request.py - on_timeout - Hard time limit (900s) exceeded for sketch_map_tool.tasks.georeference_sketch_maps[52c7f63b-2814-4618-b7af-0b1b774897c5]
sketch-map-tool-celery-1  | 2024-03-25 12:40:20,672 - ERROR - request.py - on_failure - Task handler raised error: TimeLimitExceeded(900)
sketch-map-tool-celery-1  | Traceback (most recent call last):
sketch-map-tool-celery-1  |   File "/home/smt/.conda/envs/smt/lib/python3.11/site-packages/billiard/pool.py", line 683, in on_hard_timeout
sketch-map-tool-celery-1  |     raise TimeLimitExceeded(job._timeout)
sketch-map-tool-celery-1  | billiard.einfo.ExceptionWithTraceback: 
sketch-map-tool-celery-1  | """
sketch-map-tool-celery-1  | Traceback (most recent call last):
sketch-map-tool-celery-1  |   File "/home/smt/.conda/envs/smt/lib/python3.11/site-packages/billiard/pool.py", line 683, in on_hard_timeout
sketch-map-tool-celery-1  |     raise TimeLimitExceeded(job._timeout)
sketch-map-tool-celery-1  | billiard.exceptions.TimeLimitExceeded: TimeLimitExceeded(900,)
sketch-map-tool-celery-1  | """
sketch-map-tool-celery-1  | 2024-03-25 12:40:20,672 - ERROR - request.py - on_timeout - Hard time limit (900s) exceeded for sketch_map_tool.tasks.digitize_sketches[72263cf6-27ce-4f4a-80e8-255472114184]
sketch-map-tool-celery-1  | Process 'ForkPoolWorker-2' pid:28 exited with 'signal 9 (SIGKILL)'
sketch-map-tool-celery-1  | Process 'ForkPoolWorker-4' pid:30 exited with 'signal 9 (SIGKILL)'
```

Map Frame:
![filename](https://github.com/GIScience/sketch-map-tool/assets/74006329/147ac141-8c6d-49fc-b2e3-85d619018e72)

Sketch Map:
![13](https://github.com/GIScience/sketch-map-tool/assets/74006329/b45c8e19-f4ca-4d4c-a658-6edc7f519c40)

**Comment by matthiasschaub** [comment]
Brisk is just able to find a ridiculus number of keypoints for this set of images. This leads naturaly to a longer processing time.
```
def limit_keypoints(keypoints: list, descriptors: NDArray, max_keypoints: int = 50000) -> tuple:
        """Limit the number of keypoints and descriptors """
        if len(keypoints) > max_keypoints:
            #randomly select max_keypoints
            indices = np.random.choice(len(keypoints), max_keypoints, replace=False)
            keypoints = [keypoints[i] for i in indices]
            descriptors = descriptors[indices]
            
        return keypoints, descriptors

kpts1, desc1 = limit_keypoints(kpts1, desc1)
kpts2, desc2 = limit_keypoints(kpts2, desc2)
```
(@itisacloud)

**Comment by matthiasschaub** [comment]
Other solutions could be to reduce the resolution of the input image (#421)

**Comment by solo2307** [comment]
@matthiasschaub and @itisacloud , you are both correct. Two suggested ways , the limitation of descriptors' number and reduction of image size, are ok with me. However, I would suggest to go to image resizing: 
`img_clipped = clip(cv2.resize(img_raw, (1867,1587)), temp_img)`
