### ISSUE TITLE
Simultaneously uploading multiple sketch maps (4x24) leads to sigkill in some cases

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/sketch-map-tool#410]
```
celery-1    | Process 'ForkPoolWorker-4' pid:29 exited with 'signal 9 (SIGKILL)'
celery-1    | 2024-03-25 14:50:11,685 - ERROR - request.py - on_failure - Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL) Job: 7.')
celery-1    | Traceback (most recent call last):
celery-1    |   File "/home/smt/.conda/envs/smt/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
celery-1    |     raise WorkerLostError(
celery-1    | billiard.einfo.ExceptionWithTraceback:
celery-1    | """
celery-1    | Traceback (most recent call last):
celery-1    |   File "/home/smt/.conda/envs/smt/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
celery-1    |     raise WorkerLostError(
celery-1    | billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 7.
celery-1    | """
```

**Comment by matthiasschaub** [comment]
Close in favor of #395
