### ISSUE TITLE
Uploading of 12 Sketch Maps of A1 format leads to `SQLAlchemyError('(psycopg2.OperationalError) server closed the connection unexpectedly`

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/sketch-map-tool#498]
```
celery-1  | 2024-08-26 16:07:05,100 - ERROR - builtins.py - unlock_chord - Chord '878bedb7-7840-451e-8204-cab736c47390' raised: SQLAlchemyError('(psycopg2.OperationalError) server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
celery-1  | Traceback (most recent call last):
celery-1  |   File "/home/smt/.conda/envs/smt/lib/python3.11/site-packages/celery/app/builtins.py", line 78, in unlock_chord
celery-1  |     ret = j(
celery-1  |           ^^
celery-1  |   File "/home/smt/.conda/envs/smt/lib/python3.11/site-packages/celery/result.py", line 775, in join
celery-1  |     value = result.get(
celery-1  |             ^^^^^^^^^^^
celery-1  |   File "/home/smt/.conda/envs/smt/lib/python3.11/site-packages/celery/result.py", line 247, in get
celery-1  |     self.maybe_throw(callback=callback)
celery-1  |   File "/home/smt/.conda/envs/smt/lib/python3.11/site-packages/celery/result.py", line 365, in maybe_throw
celery-1  |     self.throw(value, self._to_remote_traceback(tb))
celery-1  |   File "/home/smt/.conda/envs/smt/lib/python3.11/site-packages/celery/result.py", line 358, in throw
celery-1  |     self.on_ready.throw(*args, **kwargs)
celery-1  |   File "/home/smt/.conda/envs/smt/lib/python3.11/site-packages/vine/promises.py", line 235, in throw
celery-1  |     reraise(type(exc), exc, tb)
celery-1  |   File "/home/smt/.conda/envs/smt/lib/python3.11/site-packages/vine/utils.py", line 27, in reraise
celery-1  |     raise value
celery-1  | sqlalchemy.exc.SQLAlchemyError: (psycopg2.OperationalError) server closed the connection unexpectedly
celery-1  | 	This probably means the server terminated abnormally
celery-1  | 	before or while processing the request.
```

**Comment by matthiasschaub** [comment]
Related: https://github.com/psycopg/psycopg2/issues/1457

**Comment by matthiasschaub** [comment]
probably related to https://github.com/GIScience/sketch-map-tool/issues/399
